export const CONFIG = {
  ANIMATION_DURATION: 2000,
  FEEDBACK_DURATION: 1500,
  WHEEL_SEGMENTS: 5,
  CHOICES_COUNT: 3,
  MAX_TOKENS_DISPLAY: 20,
  SUCCESS_RATE_TARGET: 0.7,
  MIN_SPINS_FOR_SUCCESS: 8,
  HIGHLIGHT_DURATION: 800,
  QUESTION_DISPLAY_DELAY: 1000,
};

export const STORAGE_KEY = 'cvc-spin-game-state-v1';
